[package]
name = "apisix-aes"
version = "0.1.0"
edition = "2024"
[lib]
crate-type = ["cdylib"] # 生成 .so 文件
[dependencies]
aes = "0.8.4"
ecb = "0.1.2"
const-hex = "1.17.0" # 可选，用于调试
md-5 = "0.10.6"
base64 = "0.22.1"
